services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${1234}"
      POSTGRES_USER: "${mhmd}"
      POSTGRES_DB: "${snapattend}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  pgdata:
